# Generated by Django 2.1.2 on 2018-10-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25)),
                ('user_description', models.TextField(max_length=25)),
                ('FirstName', models.TextField(max_length=25)),
                ('LastName', models.TextField(max_length=25)),
                ('EmailAddress', models.TextField(max_length=50)),
                ('Password', models.TextField(max_length=50)),
                ('Group', models.TextField(max_length=50)),
            ],
        ),
    ]
